# RTMPS (TLS)
upstream mediamtx_rtmps {
  server mediamtx.displayify.svc.cluster.local:1936;
}

upstream mediamtx_webrts {
  server mediamtx.displayify.svc.cluster.local:8889;
}

upstream mediamtx_webrts_udp {
  server mediamtx.displayify.svc.cluster.local:8189;
}

server {
  listen 1936;
  proxy_pass mediamtx_rtmps;
  proxy_timeout 1h;
  proxy_connect_timeout 10s;
}

server {
  listen 8889;
  proxy_pass mediamtx_webrts;
  proxy_timeout 1h;
  proxy_connect_timeout 10s;
}

server {
  listen 8189 udp;
  proxy_pass mediamtx_webrtc_udp;
  proxy_timeout 1h;
  proxy_responses 0;
}
