server {
    listen 80;
    server_name argocd.inceptech.ru;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    http2 on;
    server_name argocd.inceptech.ru;

    ssl_certificate     /etc/nginx/certs/argocd/tls.crt;
    ssl_certificate_key /etc/nginx/certs/argocd/tls.key;

    location / {
        proxy_pass http://argocd-server.argocd.svc.cluster.local:80;
        proxy_http_version 1.1;
        proxy_set_header Host              $host;
        proxy_set_header X-Real-IP         $remote_addr;
        proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        # gRPC/WebSocket для ArgoCD CLI и UI
        proxy_set_header Upgrade           $http_upgrade;
        proxy_set_header Connection        "upgrade";
    }
}
