server {
    listen 80;
    server_name restoration.watchly.inceptech.ru;
    return 301 https://$server_name$request_uri;
}

server {
    listen 443 ssl http2;
    server_name restoration.watchly.inceptech.ru;
    
    ssl_certificate     /etc/nginx/certs/restoration-watchly/tls.crt;
    ssl_certificate_key /etc/nginx/certs/restoration-watchly/tls.key;
    
    location / {
        proxy_pass http://restoration-watchly.restoration-watchly.svc.cluster.local:80;
        proxy_set_header Host              $host;
        proxy_set_header X-Real-IP         $remote_addr;
        proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
