server {
    listen 80;
    server_name siyuan.inceptech.ru;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    http2 on;
    server_name siyuan.inceptech.ru;

    ssl_certificate     /etc/nginx/certs/siyuan/tls.crt;
    ssl_certificate_key /etc/nginx/certs/siyuan/tls.key;

    client_max_body_size 100m;
    proxy_read_timeout 600s;
    proxy_send_timeout 600s;

    location / {
        proxy_pass http://siyuan.siyuan.svc.cluster.local:6806;
        proxy_http_version 1.1;
        proxy_set_header Host              $host;
        proxy_set_header X-Real-IP         $remote_addr;
        proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        # WebSocket (SiYuan его использует)
        proxy_set_header Upgrade           $http_upgrade;
        proxy_set_header Connection        "upgrade";
    }
}
